# goreleaser.yml
# https://github.com/goreleaser/goreleaser 
build:
  main: css/main.go
  binary: css
  ldflags: -s -w -X github.com/client9/csstool/css/cmd.version={{.Version}}
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  env:
    - CGO_ENABLED=0

archives:
  - id: multi
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: 64bit
      386: 32bit
      darwin: mac

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{.Commit}}
